#! /bin/bash

#v=fail/9.mov
v=new_markers.mov
#v=reverse3_2l_3b_s_o.mov
#v=reverse2_2l_3b.mov
#v=reverse1_2l_3b.mov
#v=1list_2block_1switch.mov
#v=2hiro_1switch.mov


ROOT=$(dirname $0)/../

cd $ROOT

BIN=build/src/farcode
GDB_COMMANDS=util/gdb_commands
VIDEO=video/

export ARTOOLKIT_CONFIG="filesrc location=$VIDEO/$v ! decodebin ! ffmpegcolorspace ! capsfilter caps=video/x-raw-rgb,bpp=24 ! identity name=artoolkit ! fakesink"

#export ARTOOLKIT_CONFIG="v4l2src device=/dev/video0 use-fixed-fps=false ! ffmpegcolorspace ! capsfilter caps=video/x-raw-rgb,bpp=24 ! identity name=artoolkit ! fakesink"

gdb $BIN -x $GDB_COMMANDS

